### ISSUE TITLE
how can I fix "border chars must be one cell" error?

### ISSUE THREAD

**Issue by Pranc1ngPegasus** [rcarriga/nvim-notify#142]
My config with `dein.vim` is following.
```toml
[[plugins]]
repo = 'rcarriga/nvim-notify'
lua_add = '''
vim.notify = require("notify")
'''
```

When I ran install LSP plugin with `mason.nvim` then I got this error.
```
Error running notification service: ...e/dein/.cache/init.vim/.dein/lua/notify/windows/init.lua:284: border chars must be one cell
```

Notification was shown successfully. But wont close.
<img width="473" alt="Screen Shot 2022-10-12 at 11 58 03" src="https://user-images.githubusercontent.com/23367170/195239522-ed759c74-c03a-4b80-a441-76881ef3596f.png">
